model_config:
  vocab_size: 50257
  context_length: 256 #reduced from 1024 for CPU training
  emb_dim: 768 #dont change it
  num_heads: 12
  dropout: 0.1
  num_layers: 12
  qkv_bias: False
  

dir : 
  train_data_path : /home/amzad/Desktop/BanglaNews_GPT/dataset/prothom_data.csv # CHANGE THIS PATH TO YOUR DATASET PATH
  eval_data_path : /home/amzad/Desktop/BanglaNews_GPT/dataset/demo_text.txt # CHANGE THIS PATH TO YOUR DATASET PATH


data_loader:
  train_batch_size: 2
  eval_batch_size: 1
  num_workers: 0
  pin_memory: False
  shuffle: True
  val_split: 0.1
  seq_len: 256
  drop_last: True
 


training:
  epochs: 10
  lr: 0.0001
  eval_freq: 100
  eval_iter: 500
  start_context: "<p>গাইবান্ধার মৃত্যুদণ্ডপ্রাপ্ত সাবেক সংসদ সদস্য কর্নেল কাদের খান মারা গেছেন -" # change this to traing data context
  save_model_path: './models/bangla_gpt_model.pth'
